return {}
-- return {
--   {
--     "zbirenbaum/copilot-cmp",
--     enabled = false,
--     dependencies = "copilot.lua",
--     opts = {},
--     config = function(_, opts)
--       local copilot_cmp = require("copilot_cmp")
--       copilot_cmp.setup(opts)
--       -- attach cmp source whenever copilot attaches
--       -- fixes lazy-loading issues with the copilot cmp source
--       require("lazyvim.util").on_attach(function(client)
--         if client.name == "copilot" then
--           copilot_cmp._on_insert_enter({})
--         end
--       end)
--     end,
--   },
--   {
--     "zbirenbaum/copilot.lua",
--     cmd = "Copilot",
--     build = ":Copilot auth",
--     opts = {
--       suggestion = {
--         enabled = true,
--         auto_trigger = true
--       },
--       panel = { enabled = true },
--       filetypes = {
--         python = true,
--         php = true,
--         css = true,
--         javascript = true,
--         markdown = true,
--         help = true,
--       },
--     },
--     event = "InsertEnter",
--     -- dependencies = {
--     --   {
--     --     "zbirenbaum/copilot-cmp",
--     --     enabled = false,
--     --     after = { "copilot.lua" },
--     --     config = true,
--     --   },
--     -- },
--
--   },
--
-- }
-- --    Error  12:18:21 notify.error lazy.nvim Failed to run `config` for nvim-cmp
-- --
-- -- ...zy/LazyVim/lua/lazyvim/plugins/extras/coding/copilot.lua:75: module 'copilot_cmp.comparators' not found:
-- -- 	no field package.preload['copilot_cmp.comparators']
-- -- cache_loader: module copilot_cmp.comparators not found
-- -- cache_loader_lib: module copilot_cmp.comparators not found
-- -- 	no file './copilot_cmp/comparators.lua'
-- -- 	no file '/usr/share/luajit-2.1.0-beta3/copilot_cmp/comparators.lua'
-- -- 	no file '/usr/local/share/lua/5.1/copilot_cmp/comparators.lua'
-- -- 	no file '/usr/local/share/lua/5.1/copilot_cmp/comparators/init.lua'
-- -- 	no file '/usr/share/lua/5.1/copilot_cmp/comparators.lua'
-- -- 	no file '/usr/share/lua/5.1/copilot_cmp/comparators/init.lua'
-- -- 	no file './copilot_cmp/comparators.so'
-- -- 	no file '/usr/local/lib/lua/5.1/copilot_cmp/comparators.so'
-- -- 	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/copilot_cmp/comparators.so'
-- -- 	no file '/usr/local/lib/lua/5.1/loadall.so'
-- -- 	no file './copilot_cmp.so'
-- -- 	no file '/usr/local/lib/lua/5.1/copilot_cmp.so'
-- -- 	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/copilot_cmp.so'
-- -- 	no file '/usr/local/lib/lua/5.1/loadall.so'
-- --
-- -- # stacktrace:
-- --   - /LazyVim/lua/lazyvim/plugins/extras/coding/copilot.lua:75 _in_ **values**
-- -- {
-- --   "nvim-lualine/lualine.nvim",
-- --   optional = true,
-- --   event = "VeryLazy",
-- --   opts = function(_, opts)
-- --     local Util = require("lazyvim.util")
-- --     local colors = {
-- --       [""] = Util.fg("Special"),
-- --       ["Normal"] = Util.fg("Special"),
-- --       ["Warning"] = Util.fg("DiagnosticError"),
-- --       ["InProgress"] = Util.fg("DiagnosticWarn"),
-- --     }
-- --     table.insert(opts.sections.lualine_x, 2, {
-- --       function()
-- --         local icon = require("lazyvim.config").icons.kinds.Copilot
-- --         local status = require("copilot.api").status.data
-- --         return icon .. (status.message or "")
-- --       end,
-- --       cond = function()
-- --         local ok, clients = pcall(vim.lsp.get_active_clients, { name = "copilot", bufnr = 0 })
-- --         return ok and #clients > 0
-- --       end,
-- --       color = function()
-- --         if not package.loaded["copilot"] then
-- --           return
-- --         end
-- --         local status = require("copilot.api").status.data
-- --         return colors[status.status] or colors[""]
-- --       end,
-- --     })
-- --   end,
-- -- }
